-include $(DEPS)

# Flags to pass to the C compiler
CFLAGS += $(WFLAGS)

# Flags to pass to the C++ compiler
CXXFLAGS += $(WFLAGS)

# Proprocessor flags
CPPFLAGS += $(MK_INCLUDES) $(MK_DEFINES)

# Libraries paths
LDFLAGS += $(MK_LIBS_PATH)

ifeq ($(TARGET),ANDROID)
	CFLAGS   += --sysroot=$(ANDROID_TOOLCHAIN)/sysroot
	CXXFLAGS += --sysroot=$(ANDROID_TOOLCHAIN)/sysroot
	LDFLAGS  += -shared --sysroot=$(ANDROID_TOOLCHAIN)/sysroot
endif

# Define copy command depending on OS
ifeq ($(OS),Windows_NT)
    COPY_COMMAND ?= copy /Y
else
    COPY_COMMAND ?= cp -f
endif

# sources to include
EXTRA_SRCS_CXX ?=
EXTRA_SRCS_C ?=

# sources to exclude
EXCLUDE_SRCS ?=

#==============================================================================
# Compile only macro
#==============================================================================
# $(1) : Object to output
# $(2) : Source to compile C/C++
# $(3) : Compiler
# $(4) : Compiler preprocessor flags
# $(5) : Compiler flags
define COMPILE_ONLY
$(1) : $(2)
	$(call COMPILE_ONLY_IMPL,$(3),$(2),$(1),$(4),$(5))
endef

#==============================================================================
# Create directory
#==============================================================================
# $(1) : Directory to be create
define CREATE_DIR
$(1) :
	$(call MAKEDIR,$(1))
endef

#==============================================================================
# Generate deps
#==============================================================================
# $(1) : Deps to output
# $(2) : Source to get its deps C/C++
# $(3) : Target to generate
# $(4) : Compiler
# $(5) : Compiler preprocessor flags
# $(6) : Compiler flags
define MK_DEPS
$(1) : $(2)
	$(call MK_DEPS_IMPL,$(4),$(2),$(3),$(1),$(5),$(6))
endef

#==============================================================================
# Changes $(SRC_DIR) path to $(OBJ_DIR)
#==============================================================================
# $(1) : Source file with full path
define SOURCE_PATH_2_OBJ
$(patsubst $(SRC_DIR)%,$(OBJ_DIR)%,$(1))
endef

#==============================================================================
# Replace $(SRC_DIR) path to $(DEP_DIR)
#==============================================================================
# $(1) : Source file with full path
define SOURCE_PATH_2_DEP
$(patsubst $(SRC_DIR)%,$(DEP_DIR)%,$(1))
endef

#==============================================================================
# Replaces srcs file extension with .c.o .cc.o 
#==============================================================================
# $(1) : Full source filename
define CXXSOURCES_2_OBJS
$(call SOURCE_PATH_2_OBJ,\
$(subst .cpp,.cc.o,$(subst .cxx,.cc.o,$(subst .cc,.cc.o,$(1)))))
endef
define CSOURCES_2_OBJS
$(call SOURCE_PATH_2_OBJ,$(subst .c,.c.o,$(1)))
endef

#==============================================================================
# Replaces srcs file extension with .d 
#==============================================================================
# $(1) : Full source filename
define CXXSOURCES_2_DEPS
$(call SOURCE_PATH_2_DEP,\
$(subst .cpp,.cc.d,$(subst .cxx,.cc.d,$(subst .cc,.cc.d,$(1)))))
endef
define CSOURCES_2_DEPS
$(call SOURCE_PATH_2_DEP,$(subst .c,.c.d,$(1)))
endef

#==============================================================================
# Find sources files in a folder with the given pattern
#==============================================================================
# $(1) : Paths for search sources
# $(2) : Paterns to search
# old implementation
# $(shell find $(1) -type f -iname $(2))
FIND = $(foreach d,$(wildcard $(1:=/*)),$(call FIND,$d,$2) $(filter $(subst *,%,$2),$d))

# The path where to put the executable and the library
BUILD_PATH ?= .

# Name for the library
LIB_NAME ?= mylib

# Name of the executable
EXEC_NAME ?= app

# Name of the sources directory
SRC_DIR ?= src

# Name of the objects directory
OBJ_DIR ?= obj

# Name of the root build directory
ROOT_PATH ?= $(BUILD_PATH)

# Name of the deps directory
DEP_DIR ?= $(ROOT_PATH)/deps

# File path of the target generated library
LIB_FILE_PATH := $(BUILD_PATH)/lib$(LIB_NAME).a

# File path of the target generated exec
ifneq ($(TARGET),ANDROID)
	EXEC_FILENAME := $(EXEC_NAME)$(EXEC_EXTENSION)
	EXEC_FILE_PATH := $(BUILD_PATH)/$(EXEC_FILENAME)
else
	EXEC_FILENAME := lib$(EXEC_NAME).so
	EXEC_FILE_PATH := $(BUILD_PATH)/lib/$(ANDROID_APK_ABI)/$(EXEC_FILENAME)
	LDFLAGS  += -Wl,-soname,lib$(EXEC_FILENAME).so -Wl,--exclude-libs,libatomic.a -static-libstdc++
endif

# Required path variables
# NOTE: JAVA_HOME must be set to JDK (using OpenJDK 13)
JAVA_HOME              ?= C:/open-jdk
ANDROID_HOME           ?= C:/android-sdk
ANDROID_BUILD_TOOLS    ?= $(firstword $(wildcard $(ANDROID_HOME)/build-tools/*))
ANDROID_PLATFORM_TOOLS  = $(ANDROID_HOME)/platform-tools

# Android project configuration variables
PROJECT_NAME           ?= raylib_game
PROJECT_LIBRARY_NAME   ?= $(EXEC_NAME)
PROJECT_BUILD_PATH     ?= $(BUILD_PATH)
PROJECT_RESOURCES_PATH ?= resources

# Android app configuration variables
APP_LABEL_NAME         ?= rGame
APP_COMPANY_NAME       ?= raylib
APP_PRODUCT_NAME       ?= rgame
APP_VERSION_CODE       ?= 1
APP_VERSION_NAME       ?= 1.0
APP_ICON_LDPI          ?= assets/icons/raylib_36x36.png
APP_ICON_MDPI          ?= assets/icons/raylib_48x48.png
APP_ICON_HDPI          ?= assets/icons/raylib_72x72.png
APP_SCREEN_ORIENTATION ?= landscape
APP_KEYSTORE_PASS      ?= raylib

# Pull the raw text from template files
RAW_STRINGS = $(file < android/strings.xml)
RAW_LOADER  = $(file < android/NativeLoader.java)
RAW_MANIFEST = $(file < android/AndroidManifest.xml)

# Replace template values: $1 is the Variable Name, $2 is the Text
APPLY_TEMPLATE = $(subst {$1},$($1),$2)

# Swap the variables
STRINGS_XML = $(call APPLY_TEMPLATE,APP_LABEL_NAME,$(RAW_STRINGS))

LOADER_JAVA = $(call APPLY_TEMPLATE,APP_COMPANY_NAME,\
$(call APPLY_TEMPLATE,APP_PRODUCT_NAME,\
$(call APPLY_TEMPLATE,PROJECT_LIBRARY_NAME,\
$(RAW_LOADER))))

ANDROIDMANIFEST = $(call APPLY_TEMPLATE,APP_COMPANY_NAME,$(call APPLY_TEMPLATE,APP_PRODUCT_NAME,$(call APPLY_TEMPLATE,APP_VERSION_CODE,$(call APPLY_TEMPLATE,APP_VERSION_NAME,$(call APPLY_TEMPLATE,ANDROID_API_VERSION,$(call APPLY_TEMPLATE,APP_SCREEN_ORIENTATION,$(call APPLY_TEMPLATE,PROJECT_LIBRARY_NAME,$(RAW_MANIFEST))))))))

# Sources to compile
SRCS_CXX := $(filter-out $(EXCLUDE_SRCS),$(call FIND,$(SRC_DIR),*.cpp *.cc *.cxx)) $(EXTRA_SRCS_CXX)
SRCS_C   := $(filter-out $(EXCLUDE_SRCS),$(call FIND,$(SRC_DIR),*.c)) $(EXTRA_SRCS_C)

# Sources converted to object file
OBJS_CXX := $(call CXXSOURCES_2_OBJS,$(SRCS_CXX))
OBJS_C   := $(call CSOURCES_2_OBJS,$(SRCS_C))
OBJS     := $(OBJS_CXX) $(OBJS_C)

# Sources converted to deps
DEPS := $(call CXXSOURCES_2_DEPS,$(SRCS_CXX)) $(call CSOURCES_2_DEPS,$(SRCS_C))

# Sources directorie tree
# old implementation
# SRCS_DIRS := $(shell find $(SRC_DIR)/ -type d)
#SRCS_DIRS := $(sort $(dir $(call FIND,$(SRC_DIR),*.cpp *.hpp *.cc *.hh *.cxx *.c *.h)))
SRCS_DIRS := $(sort $(dir $(call FIND,$(SRC_DIR),*.cpp *.cc *.cxx *.c)))

# Objects directories with the same structure as src dir
OBJS_DIRS := $(call SOURCE_PATH_2_OBJ,$(SRCS_DIRS))

# Deps directories with the same structure as src dir
DEPS_DIRS := $(call SOURCE_PATH_2_DEP,$(SRCS_DIRS))

# Android directories
ANDROID_DIRS := $(BUILD_PATH)/src \
$(BUILD_PATH)/src/com \
$(BUILD_PATH)/src/com/$(APP_COMPANY_NAME) \
$(BUILD_PATH)/src/com/$(APP_COMPANY_NAME)/$(APP_PRODUCT_NAME) \
$(BUILD_PATH)/lib \
$(BUILD_PATH)/lib/$(ANDROID_APK_ABI) \
$(BUILD_PATH)/bin \
$(BUILD_PATH)/res \
$(BUILD_PATH)/res/drawable-ldpi \
$(BUILD_PATH)/res/drawable-mdpi \
$(BUILD_PATH)/res/drawable-hdpi \
$(BUILD_PATH)/res/values \
$(BUILD_PATH)/assets \
$(BUILD_PATH)/assets/$(PROJECT_RESOURCES_PATH) \
$(BUILD_PATH)/obj/screens

.PHONY: clean cleanall info run run_valgrind run_cgdb

$(BUILD_PATH):
	$(call MAKEDIR,$(BUILD_PATH))

ifneq ($(TARGET),ANDROID)
all: $(EXEC_FILE_PATH)
else
all: $(ANDROID_DIRS) \
     $(EXEC_FILE_PATH) \
     copy_project_required_libs \
     copy_project_resources \
     generate_loader_script \
     generate_android_manifest \
     generate_apk_keystore \
     config_project_package \
     compile_project_class \
     compile_project_class_dex \
     create_project_apk_package \
     zipalign_project_apk_package \
     sign_project_apk_package
endif

lib: $(LIB_FILE_PATH)

$(EXEC_FILE_PATH): $(OBJS) | $(DEPS)
	$(call LINK_EXEC,$(LD),$@,$(OBJS),$(LDLIBS),$(LDFLAGS))

$(LIB_FILE_PATH): $(OBJS) | $(DEPS)
	$(call MK_LIB,$(AR),$(ARFLAGS),$@,$(OBJS))

$(foreach O_DIR,$(OBJS_DIRS),$(eval $(call CREATE_DIR,$(O_DIR))))
$(foreach D_DIR,$(DEPS_DIRS),$(eval $(call CREATE_DIR,$(D_DIR))))
ifeq ($(TARGET),ANDROID)
$(foreach A_DIR,$(ANDROID_DIRS),$(eval $(call CREATE_DIR,$(A_DIR))))
endif

$(foreach CXX_FILE,$(SRCS_CXX),\
$(eval \
$(call COMPILE_ONLY,$(call CXXSOURCES_2_OBJS,$(CXX_FILE)),\
$(CXX_FILE),$(CXX),$(CPPFLAGS),$(CXXFLAGS))))

$(foreach C_FILE,$(SRCS_C),\
$(eval \
$(call COMPILE_ONLY,$(call CSOURCES_2_OBJS,$(C_FILE)),\
$(C_FILE),$(CC),$(CPPFLAGS),$(CFLAGS))))

run: all
ifeq ($(VALGRIND),1)
ifeq ($(ASAN),1)
	$(error "valgrind can't run with asan")
else
	valgrind $(VGFLAGS) $(EXEC_FILE)
endif
else
	$(EXEC_FILE)
endif

run_valgrind: all
ifeq ($(ASAN),1)
	$(error "valgrind can't run with asan")
else
	valgrind $(VGFLAGS) $(EXEC_FILE)
endif

run_cgdb: all
ifeq ($(ASAN),1)
	(ASAN_OPTIONS=sleep_before_dying=10:sleep_after_init=10 $(EXEC_FILE) > /dev/null 2>&1 &)
	sleep 5
	sudo cgdb -- -q -p $(shell pidof $(EXEC_FILE))
else
ifeq ($(VALGRIND),1)
	valgrind $(VGFLAGS) --vgdb=yes --vgdb-error=0 $(EXEC_FILE)
else
	cgdb $(EXEC_FILE)
endif
endif

info:
	$(info [INFO] MEMORY         : $(MEMORY))
	$(info [INFO] ASAN           : $(ASAN))
	$(info [INFO] VALGRIND       : $(VALGRIND))
	$(info [INFO] AFLAGS         : $(AFLAGS))
	$(info [INFO] VGFLAGS        : $(VGFLAGS))
	$(info [INFO] BUILD_DIR      : $(BUILD_DIR))
	$(info [INFO] BUILD_MODE_NAME: $(BUILD_MODE_NAME))
	$(info [INFO] BUILD_PATH     : $(BUILD_PATH))
	$(info [INFO] EMSCRIPTEN     : $(EMSCRIPTEN))
	$(info [INFO] MSVC           : $(MSVC))
	$(info [INFO] CLANG          : $(CLANG))
	$(info [INFO] GCC            : $(GCC))
	$(info [INFO] TARGET         : $(TARGET))
	$(info [INFO] AR             : $(AR))
	$(info [INFO] ARFLAGS        : $(ARFLAGS))
	$(info [INFO] C compiler     : $(CC))
	$(info [INFO] C++ compiler   : $(CXX))
	$(info [INFO] linker         : $(LD))
	$(info [INFO] C++ flags      : $(CXXFLAGS))
	$(info [INFO] C flags        : $(CFLAGS))
	$(info [INFO] preprocessor   : $(CPPFLAGS))
	$(info [INFO] libraries flags: $(LDFLAGS))
	$(info [INFO] libraries      : $(LDLIBS))
	$(info [INFO] C++ sources    : $(SRCS_CXX))
	$(info [INFO] C sources      : $(SRCS_C))
	$(info [INFO] Objects        : $(OBJS))
	$(info [INFO] Deps           : $(DEPS))
	$(info [INFO] Source dirs    : $(SRCS_DIRS))
	$(info [INFO] Object dirs    : $(OBJS_DIRS))
	$(info [INFO] Deps dirs      : $(DEPS_DIRS))
	$(info [INFO] EXEC           : $(EXEC_FILE_PATH))
	$(info [INFO] LIBS           : $(LIBS))

clean:
	$(call REMOVE,$(OBJS_DIRS))

cleanall: clean
	$(call REMOVE,$(EXEC_FILE_PATH))
	$(call REMOVE,$(DEPS_DIRS))

$(OBJS): | $(BUILD_PATH) $(OBJS_DIRS)
$(DEPS): | $(BUILD_PATH) $(DEPS_DIRS)

$(foreach CXX_FILE,$(SRCS_CXX),\
$(eval \
$(call MK_DEPS,$(call CXXSOURCES_2_DEPS,$(CXX_FILE)),\
$(CXX_FILE),$(call CXXSOURCES_2_OBJS,$(CXX_FILE)),$(CXX),$(CPPFLAGS),$(CXXFLAGS))))

$(foreach C_FILE,$(SRCS_C),\
$(eval \
$(call MK_DEPS,$(call CSOURCES_2_DEPS,$(C_FILE)),\
$(C_FILE),$(call CSOURCES_2_OBJS,$(C_FILE)),$(CC),$(CPPFLAGS),$(CFLAGS))))

# Copy required shared libs for integration into APK
# NOTE: If using shared libs they are loaded by generated NativeLoader.java
copy_project_required_libs:
	$(foreach LIB,$(LIBS),$(COPY_COMMAND) $(LIB) $(PROJECT_BUILD_PATH))

# Copy project required resources: strings.xml, icon.png, assets
# NOTE: Required strings.xml is generated and game resources are copied to assets folder
copy_project_resources:
	$(COPY_COMMAND) $(APP_ICON_LDPI) $(PROJECT_BUILD_PATH)/res/drawable-ldpi/icon.png
	$(COPY_COMMAND) $(APP_ICON_MDPI) $(PROJECT_BUILD_PATH)/res/drawable-mdpi/icon.png
	$(COPY_COMMAND) $(APP_ICON_HDPI) $(PROJECT_BUILD_PATH)/res/drawable-hdpi/icon.png
	$(file > $(PROJECT_BUILD_PATH)/res/values/strings.xml,$(STRINGS_XML))
	@if [ -d "$(PROJECT_RESOURCES_PATH)" ]; then cp -rf $(PROJECT_RESOURCES_PATH) $(PROJECT_BUILD_PATH)/assets/$(PROJECT_RESOURCES_PATH); fi

# Generate NativeLoader.java to load required shared libraries
# NOTE: Probably not the bet way to generate this file... but it works.
generate_loader_script:
	$(file > $(PROJECT_BUILD_PATH)/src/com/$(APP_COMPANY_NAME)/$(APP_PRODUCT_NAME)/NativeLoader.java,$(LOADER_JAVA))

# Generate AndroidManifest.xml with all the required options
# NOTE: Probably not the bet way to generate this file... but it works.
generate_android_manifest:
	$(file > $(PROJECT_BUILD_PATH)/AndroidManifest.xml,$(ANDROIDMANIFEST))

# Generate storekey for APK signing: $(PROJECT_NAME).keystore
# NOTE: Configure here your Distinguished Names (-dname) if required!
generate_apk_keystore: 
ifeq ($(OS),Windows_NT)
	if not exist $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).keystore $(JAVA_HOME)/bin/keytool -genkeypair -validity 10000 -dname "CN=$(APP_COMPANY_NAME),O=Android,C=ES" -keystore $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).keystore -storepass $(APP_KEYSTORE_PASS) -keypass $(APP_KEYSTORE_PASS) -alias $(PROJECT_NAME)Key -keyalg RSA
else
	@[ -f "$(PROJECT_BUILD_PATH)/$(PROJECT_NAME).keystore" ] || $(JAVA_HOME)/bin/keytool -genkeypair -validity 10000 -dname "CN=$(APP_COMPANY_NAME),O=Android,C=ES" -keystore $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).keystore -storepass $(APP_KEYSTORE_PASS) -keypass $(APP_KEYSTORE_PASS) -alias $(PROJECT_NAME)Key -keyalg RSA
endif

# Config project package and resource using AndroidManifest.xml and res/values/strings.xml
# NOTE: Generates resources file: src/com/$(APP_COMPANY_NAME)/$(APP_PRODUCT_NAME)/R.java
config_project_package:
	$(ANDROID_BUILD_TOOLS)/aapt package -f -m -S $(PROJECT_BUILD_PATH)/res -J $(PROJECT_BUILD_PATH)/src -M $(PROJECT_BUILD_PATH)/AndroidManifest.xml -I $(ANDROID_HOME)/platforms/android-$(ANDROID_API_VERSION)/android.jar

# Compile project .java code into .class (Java bytecode)
compile_project_class:
	$(JAVA_HOME)/bin/javac -verbose -source 1.7 -target 1.7 -d $(PROJECT_BUILD_PATH)/obj -bootclasspath $(JAVA_HOME)/jre/lib/rt.jar -classpath $(ANDROID_HOME)/platforms/android-$(ANDROID_API_VERSION)/android.jar -d $(PROJECT_BUILD_PATH)/obj $(PROJECT_BUILD_PATH)/src/com/$(APP_COMPANY_NAME)/$(APP_PRODUCT_NAME)/R.java $(PROJECT_BUILD_PATH)/src/com/$(APP_COMPANY_NAME)/$(APP_PRODUCT_NAME)/NativeLoader.java

# Compile .class files into Dalvik executable bytecode (.dex)
# NOTE: Since Android 5.0, Dalvik interpreter (JIT) has been replaced by ART (AOT)
compile_project_class_dex:
	$(ANDROID_BUILD_TOOLS)/d8 --release \
	--lib $(ANDROID_HOME)/platforms/android-$(ANDROID_API_VERSION)/android.jar \
	--output $(PROJECT_BUILD_PATH)/bin \
	$$(find $(PROJECT_BUILD_PATH)/obj -type f -name "*.class")

# Create Android APK package: bin/$(PROJECT_NAME).unsigned.apk
# NOTE: Requires compiled classes.dex and lib$(PROJECT_LIBRARY_NAME).so
# NOTE: Use -A resources to define additional directory in which to find raw asset files
create_project_apk_package:
	$(ANDROID_BUILD_TOOLS)/aapt package -f -M $(PROJECT_BUILD_PATH)/AndroidManifest.xml -S $(PROJECT_BUILD_PATH)/res -A $(PROJECT_BUILD_PATH)/assets -I $(ANDROID_HOME)/platforms/android-$(ANDROID_API_VERSION)/android.jar -F $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).unsigned.apk $(PROJECT_BUILD_PATH)/bin
	cd $(PROJECT_BUILD_PATH) && $(ANDROID_BUILD_TOOLS)/aapt add $(PROJECT_NAME).unsigned.apk lib/$(ANDROID_APK_ABI)/$(EXEC_FILENAME) $(PROJECT_SHARED_LIBS)

# Create zip-aligned APK package: $(PROJECT_NAME).apk
zipalign_project_apk_package:
	$(ANDROID_BUILD_TOOLS)/zipalign -p -f 4 $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).unsigned.apk $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).aligned.apk

# Create signed APK package using generated Key: bin/$(PROJECT_NAME).signed.apk
sign_project_apk_package:
	$(ANDROID_BUILD_TOOLS)/apksigner sign --ks $(PROJECT_BUILD_PATH)/$(PROJECT_NAME).keystore \
	--ks-pass pass:$(APP_KEYSTORE_PASS) \
	--out $(PROJECT_NAME).apk \
	$(PROJECT_BUILD_PATH)/$(PROJECT_NAME).aligned.apk

# Install $(PROJECT_NAME).apk to default emulator/device
# NOTE: Use -e (emulator) or -d (device) parameters if required
install:
	$(ANDROID_PLATFORM_TOOLS)/adb install $(PROJECT_NAME).apk

# Check supported ABI for the device (armeabi-v7a, arm64-v8a, x86, x86_64)
check_device_abi:
	$(ANDROID_PLATFORM_TOOLS)/adb shell getprop ro.product.cpu.abi

# Monitorize output log coming from device, only raylib tag
logcat:
	$(ANDROID_PLATFORM_TOOLS)/adb logcat -c
	$(ANDROID_PLATFORM_TOOLS)/adb logcat raylib:V *:S

# Install and monitorize $(PROJECT_NAME).apk to default emulator/device
deploy:
	$(ANDROID_PLATFORM_TOOLS)/adb install $(PROJECT_NAME).apk
	$(ANDROID_PLATFORM_TOOLS)/adb logcat -c
	$(ANDROID_PLATFORM_TOOLS)/adb logcat raylib:V *:S
